{"name": "test_logout", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../datas/userinfo.yaml'", "trace": "self = <test_login.TestLogin object at 0x10ead1bb0>\n\n    def test_logout(self):\n>       self.login.logout()\n\ntest_login.py:29: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n../api_page/login_page.py:46: in logout\n    WeWorkUtils.save_user_info(self,data)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <api_page.login_page.LoginPage object at 0x10eaf4ca0>, data = {}\n\n    def save_user_info(self,data):\n>       with open('../datas/userinfo.yaml', mode='w', encoding='utf-8') as file:\nE       FileNotFoundError: [Errno 2] No such file or directory: '../datas/userinfo.yaml'\n\n../api_page/wework_utils.py:21: FileNotFoundError"}, "start": 1606288926939, "stop": 1606288926939, "uuid": "ea937a5e-553a-4321-b891-a3c2321fdb36", "historyId": "2a5f5bbaa3dd728f6d21d22f78f5d4b5", "testCaseId": "db2319712f68f1004528a71c8d391180", "fullName": "test_login.TestLogin#test_logout", "labels": [{"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "Jammy-MacBook-Pro.local"}, {"name": "thread", "value": "91017-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login"}]}