{"name": "test_login", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../datas/userinfo.yaml'", "trace": "self = <test_login.TestLogin object at 0x10eac95e0>\n\n    def test_login(self):\n        params = {\n            \"cellphone\": 16896689007,\n            \"smsCode\":1234\n        }\n>       login_message = self.login.login(params)\n\ntest_login.py:25: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n../api_page/login_page.py:29: in login\n    WeWorkUtils.save_user_info(self, data)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <api_page.login_page.LoginPage object at 0x10eaf4ca0>\ndata = {'hasContract': '1', 'token': '2a8e2be490e12ac3efe41beb40c59094', 'userInfo': {'acc_id': '16896689007', 'appList': 0, 'callLog': 0, 'cellphone': '16896689007', ...}}\n\n    def save_user_info(self,data):\n>       with open('../datas/userinfo.yaml', mode='w', encoding='utf-8') as file:\nE       FileNotFoundError: [Errno 2] No such file or directory: '../datas/userinfo.yaml'\n\n../api_page/wework_utils.py:21: FileNotFoundError"}, "attachments": [{"name": "stdout", "source": "0861ad2b-c808-4fa8-a242-5fd2c15e5397-attachment.txt", "type": "text/plain"}], "start": 1606288926746, "stop": 1606288926932, "uuid": "9074cfd3-0e52-46cd-b583-ced0e6cb778c", "historyId": "e18e73dc148eb22430ae8d87ce2af2bb", "testCaseId": "b62a022e3184708d2d40012e446c9b1d", "fullName": "test_login.TestLogin#test_login", "labels": [{"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "Jammy-MacBook-Pro.local"}, {"name": "thread", "value": "91017-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login"}]}